name: agro_bio_tech_pc
description: Gerador de laudos
publish_to: "none"
version: 1.0.0+1




flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand.ttf
       

environment:
  sdk: ">=3.3.1 <4.0.0"



dependencies:
  path_provider: ^2.1.2 
  provider: ^6.1.2
  pdf: ^3.10.8
  share_plus: ^9.0.0
  image_picker: ^1.1.2
  open_file: ^3.3.2




dev_dependencies:
  flutter_launcher_icons: ^0.13.1


  
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

